/* Generated By:JavaCC: Do not edit this line. SimpleCConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleCConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPARENT = 5;
  /** RegularExpression Id. */
  int RPARENT = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
  };

}
